apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.5
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: postgres
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: WORDPRESS_DB_PASSWORD_FILE           # changed here
          value: /run/secrets/postgres/POSTGRES_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
        - name: postgres-secret-volume                  # added secret mount
          mountPath: /run/secrets/postgres
          readOnly: true
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
      - name: postgres-secret-volume
        secret:
          secretName: postgres-secret
